# Generated by Django 5.0.1 on 2024-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('parcours', models.CharField(max_length=70)),
                ('filiere', models.CharField(max_length=70)),
                ('tel', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sexe', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=3000)),
                ('date', models.DateField()),
            ],
        ),
    ]
