# Generated by Django 5.0.1 on 2024-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_alter_etudiant_image_alter_etudiant_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Actif',
            field=models.BooleanField(default=True),
        ),
    ]
