# Generated by Django 5.0.1 on 2024-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0003_etudiant_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='tel',
        ),
    ]
