# Generated by Django 5.0.1 on 2024-01-26 22:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0004_remove_etudiant_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
