# Generated by Django 5.0.1 on 2024-01-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0005_etudiant_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'etudiant', 'verbose_name_plural': 'etudiiants'},
        ),
    ]
