# Generated by Django 5.0.1 on 2024-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0008_alter_etudiant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(default='Masculin', max_length=70),
        ),
    ]
