# Generated by Django 5.0.1 on 2024-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0009_alter_etudiant_date_alter_etudiant_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
