# Generated by Django 5.0.1 on 2024-10-06 21:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0011_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sexe', models.CharField(choices=[('Masculin', 'M'), ('Feminin', 'F')], max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
            ],
        ),
    ]
