# Generated by Django 5.0.1 on 2024-10-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0012_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
