# Generated by Django 5.0.1 on 2024-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0015_alter_commander_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commander',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=100),
        ),
    ]
