# Generated by Django 5.0.1 on 2024-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0016_alter_commander_email_alter_commander_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=19650, max_digits=20000),
        ),
    ]
