# Generated by Django 5.0.1 on 2024-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0018_commander_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commander',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='commander',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
